import './globals.css'
import { Inter } from 'next/font/google'
import styles from "./layout.module.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.png" sizes="7x5" />
      <body className={inter.className}>
        <header className={styles.header}>
          <button className={styles.profile}>
            <img src="https://icons.veryicon.com/png/o/miscellaneous/administration/person-16.png" className={styles.profileP}/>  
            John Doe
          </button>
          <button className={styles.logoB}>
            <img src="favicon.png" className={styles.logo} />
          </button>
        </header>
        {children}
      </body>
    </html>
  )
}
